#!/bin/csh

echo 'Setting up files' 

# Manually adjust path in Setup files
sed -e "s|HERE|${PWD}|" src/Setup/chooser_orig.f > src/Setup/chooser.f 


sed -e "s|HERE|${PWD}|" src/Setup/read_interface_settings_orig.f > src/Setup/read_interface_settings.f 

sed -e "s|HERE|${PWD}|" src/Need/read_cuts_orig.f > src/Need/read_cuts.f 
sed -e "s|HERE|${PWD}|" src/Need/read_params_orig.f > src/Need/read_params.f 
sed -e "s|HERE|${PWD}|" src/Need/higgsp_orig.f > src/Need/higgsp.f 

echo 'Finished Setup,, making '

make

